### ISSUE TITLE
Can't compile FATFS

### ISSUE THREAD

**Issue by CaydendW** [abbrev/fatfs#6]
When I try to compile my project I get all of these errors:
```/usr/bin/ld: diskio.o: in function `disk_status':
diskio.c:(.text+0x31): undefined reference to `MMC_disk_status'
/usr/bin/ld: diskio.c:(.text+0x41): undefined reference to `RAM_disk_status'
/usr/bin/ld: diskio.c:(.text+0x51): undefined reference to `USB_disk_status'
/usr/bin/ld: diskio.o: in function `disk_initialize':
diskio.c:(.text+0x91): undefined reference to `MMC_disk_initialize'
/usr/bin/ld: diskio.c:(.text+0xa1): undefined reference to `RAM_disk_initialize'
/usr/bin/ld: diskio.c:(.text+0xb1): undefined reference to `USB_disk_initialize'
/usr/bin/ld: diskio.o: in function `disk_read':
diskio.c:(.text+0x100): undefined reference to `MMC_disk_read'
/usr/bin/ld: diskio.c:(.text+0x128): undefined reference to `RAM_disk_read'
/usr/bin/ld: diskio.c:(.text+0x150): undefined reference to `USB_disk_read'
/usr/bin/ld: diskio.o: in function `disk_write':
diskio.c:(.text+0x1b0): undefined reference to `MMC_disk_write'
/usr/bin/ld: diskio.c:(.text+0x1d8): undefined reference to `RAM_disk_write'
/usr/bin/ld: diskio.c:(.text+0x200): undefined reference to `USB_disk_write'
/usr/bin/ld: ff.o: in function `f_open':
ff.c:(.text+0x1a1c): undefined reference to `get_fattime'
/usr/bin/ld: ff.o: in function `f_sync':
ff.c:(.text+0x20f3): undefined reference to `get_fattime'
/usr/bin/ld: ff.o: in function `f_mkdir':
ff.c:(.text+0x2e10): undefined reference to `get_fattime'
/usr/bin/ld: ff.c:(.text+0x2f01): undefined reference to `get_fattime'
/usr/bin/ld: ff.c:(.text+0x2f1d): undefined reference to `get_fattime'
/usr/bin/ld: ff.o:ff.c:(.text+0x2f31): more undefined references to `get_fattime' follow
collect2: error: ld returned 1 exit status
ld: diskio.o: in function `disk_status':
diskio.c:(.text+0x31): undefined reference to `MMC_disk_status'
ld: diskio.c:(.text+0x41): undefined reference to `RAM_disk_status'
ld: diskio.c:(.text+0x51): undefined reference to `USB_disk_status'
ld: diskio.o: in function `disk_initialize':
diskio.c:(.text+0x91): undefined reference to `MMC_disk_initialize'
ld: diskio.c:(.text+0xa1): undefined reference to `RAM_disk_initialize'
ld: diskio.c:(.text+0xb1): undefined reference to `USB_disk_initialize'
ld: diskio.o: in function `disk_read':
diskio.c:(.text+0x100): undefined reference to `MMC_disk_read'
ld: diskio.c:(.text+0x128): undefined reference to `RAM_disk_read'
ld: diskio.c:(.text+0x150): undefined reference to `USB_disk_read'
ld: diskio.o: in function `disk_write':
diskio.c:(.text+0x1b0): undefined reference to `MMC_disk_write'
ld: diskio.c:(.text+0x1d8): undefined reference to `RAM_disk_write'
ld: diskio.c:(.text+0x200): undefined reference to `USB_disk_write'
ld: ff.o: in function `f_open':
ff.c:(.text+0x1a1c): undefined reference to `get_fattime'
ld: ff.o: in function `f_sync':
ff.c:(.text+0x20f3): undefined reference to `get_fattime'
ld: ff.o: in function `f_mkdir':
ff.c:(.text+0x2e10): undefined reference to `get_fattime'
ld: ff.c:(.text+0x2f01): undefined reference to `get_fattime'
ld: ff.c:(.text+0x2f1d): undefined reference to `get_fattime'
ld: ff.o:ff.c:(.text+0x2f31): more undefined references to `get_fattime' follow```
I have tried changing the ffconf.h file but I still get the same results every time.
Is there something I am missing?
Thank you for the help in advanced!

**Comment by Kawa-oneechan** [comment]
Your `diskio.c` media access interface seems to be very incomplete. It's missing `get_fattime` and its `disk_XXX` functions appear to call into other functions that don't exist. That's basically what this error vomit means, and editing `ffconf.h` wouldn't help much.

`get_fattime` would be the least important and easiest to fix -- just set `FF_FS_NORTC` to 1 in `ffconf.h` and provide a default date, but your `disk_XXX` functions are a bigger issue. I'd wish I could help, but all I did with FatFS was pretty simple and all you've given to go on is a linker's errors.

**Comment by CaydendW** [comment]
Ok thank you for your help. I'll try and figure this out.

**Comment by Kawa-oneechan** [comment]
Good luck!
